### ISSUE TITLE
Styling on HTML

### ISSUE THREAD

**Issue by davechu** [garethrees/landing-page#3]
Hi Gareth, 
I found a tiny CSS issue. When I tried re-sizing the window, the background colors of the page suddenly looked wacked. I was going cuckoo until I finally found the cause - having a background color on the HTML tag. All I had to do was stick the background color onto BODY instead, and that fixed it - the whole thing began to flex just fine. 

Overall, a very nice template, thanks!

**Comment by garethrees** [comment]
Thanks! Happy to accept a pull request if that's easy enough for you to do. If not I'll take a look at fixing this when I get chance.
